### ISSUE TITLE
Error When Running ot-sim Test Example Using hivemind: Issue with Bus Activation

### ISSUE THREAD

**Issue by mzinfobeyond** [patsec/ot-sim#4]
Hi there, I'm new to using ot-sim. I'm attempting to run the ot-sim test example using hivemind. However, when I execute hivemind Procfile.single, I encounter the following error:

```
broker | Running...
cpu    | Running...
dss    | Running...
cpu    | 2023/08/30 16:07:15 [CPU] starting dnp3 module
cpu    | 2023/08/30 16:07:15 [CPU] starting io module
cpu    | 2023/08/30 16:07:15 [CPU] starting modbus module
cpu    | 2023/08/30 16:07:15 [CPU] starting node-red module
cpu    | 2023/08/30 16:07:15 [CPU] starting backplane module
cpu    | 2023/08/30 16:07:15 [CPU] starting telnet module
cpu    | 2023/08/30 16:07:15 [LOG] configuring DNP3 server dnp3-outstation
cpu    | 2023/08/30 16:07:15 [LOG] ms(1693426035111) INFO    dnp3-outstation - Listening on: 127.0.0.1:20000
cpu    | 2023/08/30 16:07:15 [LOG] adding outstation 1 --> 1024
cpu    | 2023/08/30 16:07:15 [LOG] starting DNP3 server dnp3-outstation
cpu    | 2023/08/30 16:07:15 [LOG] Error starting Node-RED module: starting node-red: starting Node-RED: module executable does not exist at node-red
cpu    | 2023/08/30 16:07:15 [CPU] [ERROR] node-red module died and requested no restart
cpu    | 2023/08/30 16:07:15 [LOG] [dnp3-outstation] updated binary input 0 to 0
cpu    | 2023/08/30 16:07:15 [LOG] [dnp3-outstation] updated binary output 10 to 0
cpu    | 2023/08/30 16:07:15 [LOG] [dnp3-outstation] updated analog input 0 to 0
broker | HELICS broker started
cpu    | 2023/08/30 16:07:15 [RUNTIME] {"version": "v1", "kind": "Status", "metadata": {"sender": "helics-federate"}, "contents": {"measurements": [{"tag": "bus-692.voltage", "value": -1e+49, "ts": 0}, {"tag": "line-650632.kW", "value": -1e+49, "ts": 0}, {"tag": "line-650632.kVAR", "value": -1e+49, "ts": 0}, {"tag": "line-650632.closed", "value": 1.0, "ts": 0}, {"tag": "switch-671692.closed", "value": 1.0, "ts": 0}]}}
cpu    | 2023/08/30 16:07:15 [LOG] [modbus-outstation] setting tag bus-692.voltage to value -9999999999999999464902769475481793196872414789632.000000
cpu    | 2023/08/30 16:07:15 [LOG] [modbus-outstation] setting tag line-650632.kW to value -9999999999999999464902769475481793196872414789632.000000
cpu    | 2023/08/30 16:07:15 [LOG] [modbus-outstation] setting tag line-650632.kVAR to value -9999999999999999464902769475481793196872414789632.000000
cpu    | 2023/08/30 16:07:15 [LOG] [modbus-outstation] setting tag line-650632.closed to value 1.000000
cpu    | 2023/08/30 16:07:15 [LOG] [modbus-outstation] setting tag switch-671692.closed to value 1.000000
cpu    | 2023/08/30 16:07:15 [LOG] [dnp3-outstation] status received for tag line-650632.kW
cpu    | 2023/08/30 16:07:15 [LOG] [dnp3-outstation] status received for tag line-650632.closed
dss    | [2023-08-30 16:07:15.579] [console] [error] OpenDSS (131073)[1]::OpenDSS sent abort message: 'Traceback (most recent call last):
dss    |   File "testing/e2e/helics/opendss-federate.py", line 282, in <module>
dss    |     federate1.run()
dss    |   File "/usr/local/lib/python3.8/dist-packages/otsim/helics_helper/__init__.py", line 229, in run
dss    |     self.action_publications(self.values.send, self.current_time)
dss    |   File "testing/e2e/helics/opendss-federate.py", line 123, in action_publications
dss    |     dss.Circuit.SetActiveBus(name)
dss    |   File "/usr/local/lib/python3.8/dist-packages/opendssdirect/Circuit.py", line 90, in SetActiveBus
dss    |     return CheckForError(lib.Circuit_SetActiveBus(BusName))
dss    |   File "/usr/local/lib/python3.8/dist-packages/dss/_cffi_api_util.py", line 81, in CheckForError
dss    |     raise DSSException(error_num, self._get_string(self._lib.Error_Get_Description()))
dss    | dss._cffi_api_util.DSSException: (8989, 'No active bus found! Activate one and retry.')'
dss    | [2023-08-30 16:07:15.579] [console] [error] 74b0d022-5050-4c7b-b40a-5d054ed29f81 (1879048193)[t=1]::OpenDSS sent abort message: 'Traceback (most recent call last):
dss    |   File "testing/e2e/helics/opendss-federate.py", line 282, in <module>
dss    |     federate1.run()
dss    |   File "/usr/local/lib/python3.8/dist-packages/otsim/helics_helper/__init__.py", line 229, in run
dss    |     self.action_publications(self.values.send, self.current_time)
dss    |   File "testing/e2e/helics/opendss-federate.py", line 123, in action_publications
dss    |     dss.Circuit.SetActiveBus(name)
dss    |   File "/usr/local/lib/python3.8/dist-packages/opendssdirect/Circuit.py", line 90, in SetActiveBus
dss    |     return CheckForError(lib.Circuit_SetActiveBus(BusName))
dss    |   File "/usr/local/lib/python3.8/dist-packages/dss/_cffi_api_util.py", line 81, in CheckForError
dss    |     raise DSSException(error_num, self._get_string(self._lib.Error_Get_Description()))
dss    | dss._cffi_api_util.DSSException: (8989, 'No active bus found! Activate one and retry.')'
dss    | [2023-08-30 16:07:15.579] [console] [error] 74b0d022-5050-4c7b-b40a-5d054ed29f81 (1879048193)[t=1]::74b0d022-5050-4c7b-b40a-5d054ed29f81 sent abort message: 'Traceback (most recent call last):
dss    |   File "testing/e2e/helics/opendss-federate.py", line 282, in <module>
dss    |     federate1.run()
dss    |   File "/usr/local/lib/python3.8/dist-packages/otsim/helics_helper/__init__.py", line 229, in run
dss    |     self.action_publications(self.values.send, self.current_time)
dss    |   File "testing/e2e/helics/opendss-federate.py", line 123, in action_publications
dss    |     dss.Circuit.SetActiveBus(name)
dss    |   File "/usr/local/lib/python3.8/dist-packages/opendssdirect/Circuit.py", line 90, in SetActiveBus
broker | [2023-08-30 16:07:15.579] [console] [error] ::OpenDSS sent abort message: 'Traceback (most recent call last):
broker |   File "testing/e2e/helics/opendss-federate.py", line 282, in <module>
dss    |     return CheckForError(lib.Circuit_SetActiveBus(BusName))
dss    |   File "/usr/local/lib/python3.8/dist-packages/dss/_cffi_api_util.py", line 81, in CheckForError
broker |     federate1.run()
broker |   File "/usr/local/lib/python3.8/dist-packages/otsim/helics_helper/__init__.py", line 229, in run
broker |     self.action_publications(self.values.send, self.current_time)
broker |   File "testing/e2e/helics/opendss-federate.py", line 123, in action_publications
broker |     dss.Circuit.SetActiveBus(name)
broker |   File "/usr/local/lib/python3.8/dist-packages/opendssdirect/Circuit.py", line 90, in SetActiveBus
broker |     return CheckForError(lib.Circuit_SetActiveBus(BusName))
broker |   File "/usr/local/lib/python3.8/dist-packages/dss/_cffi_api_util.py", line 81, in CheckForError
broker |     raise DSSException(error_num, self._get_string(self._lib.Error_Get_Description()))
broker | dss._cffi_api_util.DSSException: (8989, 'No active bus found! Activate one and retry.')'
broker | [2023-08-30 16:07:15.579] [console] [error] 121200-27THf-Wctxb-CfiyC-CQoG0 (1)[connected_error]::OpenDSS sent abort message: 'Traceback (most recent call last):
broker |   File "testing/e2e/helics/opendss-federate.py", line 282, in <module>
broker |     federate1.run()
dss    |     raise DSSException(error_num, self._get_string(self._lib.Error_Get_Description()))
broker |   File "/usr/local/lib/python3.8/dist-packages/otsim/helics_helper/__init__.py", line 229, in run
dss    | dss._cffi_api_util.DSSException: (8989, 'No active bus found! Activate one and retry.')'
broker |     self.action_publications(self.values.send, self.current_time)
broker |   File "testing/e2e/helics/opendss-federate.py", line 123, in action_publications
broker |     dss.Circuit.SetActiveBus(name)
broker |   File "/usr/local/lib/python3.8/dist-packages/opendssdirect/Circuit.py", line 90, in SetActiveBus
broker |     return CheckForError(lib.Circuit_SetActiveBus(BusName))
broker |   File "/usr/local/lib/python3.8/dist-packages/dss/_cffi_api_util.py", line 81, in CheckForError
broker |     raise DSSException(error_num, self._get_string(self._lib.Error_Get_Description()))
broker | dss._cffi_api_util.DSSException: (8989, 'No active bus found! Activate one and retry.')'
cpu    | 2023/08/30 16:07:15 [LOG] [2023-08-30 16:07:15.580] [console] [error] 2707ebab-a815-4cfd-83c9-61f84f2533f6 (1879048192)[t=1]::OpenDSS sent abort message: 'Traceback (most recent call last):
cpu    | 2023/08/30 16:07:15 [LOG]   File "testing/e2e/helics/opendss-federate.py", line 282, in <module>
cpu    | 2023/08/30 16:07:15 [LOG]     federate1.run()
cpu    | 2023/08/30 16:07:15 [LOG]   File "/usr/local/lib/python3.8/dist-packages/otsim/helics_helper/__init__.py", line 229, in run
cpu    | 2023/08/30 16:07:15 [LOG]     self.action_publications(self.values.send, self.current_time)
cpu    | 2023/08/30 16:07:15 [LOG]   File "testing/e2e/helics/opendss-federate.py", line 123, in action_publications
cpu    | 2023/08/30 16:07:15 [LOG]     dss.Circuit.SetActiveBus(name)
cpu    | 2023/08/30 16:07:15 [LOG]   File "/usr/local/lib/python3.8/dist-packages/opendssdirect/Circuit.py", line 90, in SetActiveBus
cpu    | 2023/08/30 16:07:15 [LOG]     return CheckForError(lib.Circuit_SetActiveBus(BusName))
cpu    | 2023/08/30 16:07:15 [LOG]   File "/usr/local/lib/python3.8/dist-packages/dss/_cffi_api_util.py", line 81, in CheckForError
cpu    | 2023/08/30 16:07:15 [LOG]     raise DSSException(error_num, self._get_string(self._lib.Error_Get_Description()))
cpu    | 2023/08/30 16:07:15 [LOG] dss._cffi_api_util.DSSException: (8989, 'No active bus found! Activate one and retry.')'
cpu    | 2023/08/30 16:07:15 [LOG] [2023-08-30 16:07:15.580] [console] [error] ot-sim-io (131072)[1]::OpenDSS sent abort message: 'Traceback (most recent call last):
cpu    | 2023/08/30 16:07:15 [LOG]   File "testing/e2e/helics/opendss-federate.py", line 282, in <module>
cpu    | 2023/08/30 16:07:15 [LOG]     federate1.run()
cpu    | 2023/08/30 16:07:15 [LOG]   File "/usr/local/lib/python3.8/dist-packages/otsim/helics_helper/__init__.py", line 229, in run
cpu    | 2023/08/30 16:07:15 [LOG]     self.action_publications(self.values.send, self.current_time)
cpu    | 2023/08/30 16:07:15 [LOG]   File "testing/e2e/helics/opendss-federate.py", line 123, in action_publications
cpu    | 2023/08/30 16:07:15 [LOG]     dss.Circuit.SetActiveBus(name)
cpu    | 2023/08/30 16:07:15 [LOG]   File "/usr/local/lib/python3.8/dist-packages/opendssdirect/Circuit.py", line 90, in SetActiveBus
cpu    | 2023/08/30 16:07:15 [LOG]     return CheckForError(lib.Circuit_SetActiveBus(BusName))
cpu    | 2023/08/30 16:07:15 [LOG]   File "/usr/local/lib/python3.8/dist-packages/dss/_cffi_api_util.py", line 81, in CheckForError
cpu    | 2023/08/30 16:07:15 [LOG]     raise DSSException(error_num, self._get_string(self._lib.Error_Get_Description()))
cpu    | 2023/08/30 16:07:15 [LOG] dss._cffi_api_util.DSSException: (8989, 'No active bus found! Activate one and retry.')'
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR] Exception in thread Thread-3:
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR] Traceback (most recent call last):
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]     self.run()
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]   File "/usr/lib/python3.8/threading.py", line 870, in run
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]     self._target(*self._args, **self._kwargs)
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]   File "/usr/local/lib/python3.8/dist-packages/otsim/helics_helper/__init__.py", line 221, in run
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]     granted_time = h.helicsFederateRequestTime(self._federate, t)
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]   File "/usr/local/lib/python3.8/dist-packages/helics/capi.py", line 4484, in helicsFederateRequestTime
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]     raise HelicsException("[" + str(err.error_code) + "] " + ffi.string(err.message).decode())
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR] helics.capi.HelicsException: [-101] OpenDSS sent abort message: 'Traceback (most recent call last):
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]   File "testing/e2e/helics/opendss-federate.py", line 282, in <module>
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]     federate1.run()
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]   File "/usr/local/lib/python3.8/dist-packages/otsim/helics_helper/__init__.py", line 229, in run
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]     self.action_publications(self.values.send, self.current_time)
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]   File "testing/e2e/helics/opendss-federate.py", line 123, in action_publications
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]     dss.Circuit.SetActiveBus(name)
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]   File "/usr/local/lib/python3.8/dist-packages/opendssdirect/Circuit.py", line 90, in SetActiveBus
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]     return CheckForError(lib.Circuit_SetActiveBus(BusName))
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]   File "/usr/local/lib/python3.8/dist-packages/dss/_cffi_api_util.py", line 81, in CheckForError
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR]     raise DSSException(error_num, self._get_string(self._lib.Error_Get_Description()))
cpu    | 2023/08/30 16:07:15 [LOG] [ERROR] dss._cffi_api_util.DSSException: (8989, 'No active bus found! Activate one and retry.')'
dss    | Traceback (most recent call last):
dss    |   File "testing/e2e/helics/opendss-federate.py", line 282, in <module>
dss    |     federate1.run()
dss    |   File "/usr/local/lib/python3.8/dist-packages/otsim/helics_helper/__init__.py", line 229, in run
dss    |     self.action_publications(self.values.send, self.current_time)
dss    |   File "testing/e2e/helics/opendss-federate.py", line 123, in action_publications
dss    |     dss.Circuit.SetActiveBus(name)
dss    |   File "/usr/local/lib/python3.8/dist-packages/opendssdirect/Circuit.py", line 90, in SetActiveBus
dss    |     return CheckForError(lib.Circuit_SetActiveBus(BusName))
dss    |   File "/usr/local/lib/python3.8/dist-packages/dss/_cffi_api_util.py", line 81, in CheckForError
dss    |     raise DSSException(error_num, self._get_string(self._lib.Error_Get_Description()))
dss    | dss._cffi_api_util.DSSException: (8989, 'No active bus found! Activate one and retry.')
dss    | exit status 1
cpu    | Interrupting...
```
It seems like the error is related to activating the bus. Could someone please provide guidance on what might be going wrong in this case? Thank you!

**Comment by activeshadow** [comment]
Hi @mzinfobeyond thanks for the bug report. Can you let me know if you're using a Docker container to run the example? If so, how did you build the container image?

**Comment by mzinfobeyond** [comment]
Thanks @activeshadow for quick reply. I build from the source. I followed the instruction outlined [here](https://ot-sim.patsec.dev/getting_started/) Instead of using overmind, I opted for hivemind (hivemind Procfile.single) to enable log tracking. When I used the overmind, I am getting following message.
```
user@mzinfobeyond:/home/user/ot-sim# overmind start -D -f Procfile.single
system | Tmux socket name: overmind-ot-sim-Ird7VAKe_4Esk-QrBMN5z4
system | Tmux session ID: ot-sim
system | Listening at ./.overmind.sock
system | Daemonized. Use `overmind echo` to view logs and `overmind quit` to gracefully quit daemonized instance
user@mzinfobeyond:/home/user/ot-sim# overmind echo
overmind: dial unix ./.overmind.sock: connect: no such file or directory
```
Thanks again!

**Comment by activeshadow** [comment]
@mzinfobeyond please see if the `fix-tests` branch now works for you. If it does, I'll update the official documentation as well.

**Comment by mzinfobeyond** [comment]
Thank you @activeshadow for the test updates. I'm now able to execute the tests successfully. However, I'm encountering an issue where the value from 30000 is being shown as 0 instead of 192. Here's the outcome:

```
user@mzinfobeyond:/home/user/ot-sim-test/ot-sim# mbpoll -0 -1 -t 3 -r 30000 -c 1 -p 5502 localhost
Protocol configuration: Modbus TCP
Slave configuration...: address = [1]
                        start reference = 30000, count = 1
Communication.........: localhost, port 5502, t/o 1.00 s, poll rate 1000 ms
Data type.............: 16-bit register, input register table

-- Polling slave 1...
[30000]: 	0
```
Here is the `overmind echo` output:

```
system | Echo #1 opened
cpu    | 2023/08/31 11:06:06 [RUNTIME] {"version": "v1", "kind": "Status", "metadata": {"sender": "helics-federate"}, "contents": {"measurements": [{"tag": "line-650632.kW", "value": 0.0, "ts": 0}, {"tag": "line-650632.kVAR", "value": 0.0, "ts": 0}, {"tag": "line-650632.closed", "value": 1.0, "ts": 0}, {"tag": "switch-671692.closed", "value": 1.0, "ts": 0}]}}
cpu    | 2023/08/31 11:06:06 [LOG] [modbus-outstation] setting tag line-650632.kW to value 0.000000
cpu    | 2023/08/31 11:06:06 [LOG] [modbus-outstation] setting tag line-650632.kVAR to value 0.000000
cpu    | 2023/08/31 11:06:06 [LOG] [modbus-outstation] setting tag line-650632.closed to value 1.000000
cpu    | 2023/08/31 11:06:06 [LOG] [modbus-outstation] setting tag switch-671692.closed to value 1.000000
cpu    | 2023/08/31 11:06:06 [LOG] [dnp3-outstation] status received for tag line-650632.kW
cpu    | 2023/08/31 11:06:06 [LOG] [dnp3-outstation] status received for tag line-650632.closed
cpu    | 2023/08/31 11:06:06 [LOG] [dnp3-outstation] updated binary input 0 to 1
cpu    | 2023/08/31 11:06:06 [LOG] [dnp3-outstation] updated binary output 10 to 1
cpu    | 2023/08/31 11:06:06 [LOG] [dnp3-outstation] updated analog input 0 to 0
cpu    | 2023/08/31 11:06:07 [LOG] [modbus-outstation] setting tag line-650632.kW to value 0.000000
cpu    | 2023/08/31 11:06:07 [LOG] [modbus-outstation] setting tag line-650632.kVAR to value 0.000000
cpu    | 2023/08/31 11:06:07 [LOG] [modbus-outstation] setting tag line-650632.closed to value 1.000000
cpu    | 2023/08/31 11:06:07 [LOG] [modbus-outstation] setting tag switch-671692.closed to value 1.000000
cpu    | 2023/08/31 11:06:07 [LOG] [dnp3-outstation] status received for tag line-650632.kW
cpu    | 2023/08/31 11:06:07 [LOG] [dnp3-outstation] status received for tag line-650632.closed

```
Do I need to update line-650632.kW value? Thank you for your help.

**Comment by activeshadow** [comment]
Hi @mzinfobeyond you should not have to set anything. The line flow should start out being non-zero. Can you provide logs for the dss process? That's what's actually generating the line flow values via steady state power flow simulation.

**Comment by activeshadow** [comment]
Nevermind @mzinfobeyond it looks like the dss process doesn't generate any logs. I just ran `overmind start -f Procfile.single -D` and then connected to the `cpu` process and I'm seeing values for line flow without doing anything else.

**Comment by activeshadow** [comment]
This is what I'm seeing...

![image](https://github.com/patsec/ot-sim/assets/9335331/55e0f668-b435-4531-a6b6-9a4fc26d52e9)

**Comment by mzinfobeyond** [comment]
Hello @activeshadow,

Thank you for your prompt response. I've attempted various steps, including restarting, reinstalling, and even using Docker. Unfortunately, I'm still encountering the issue where the kvar and kw values are not being captured correctly. My results remain same:

From cpu:

```
cpu    | 2023/09/01 10:23:12 [RUNTIME] {"version": "v1", "kind": "Status", "metadata": {"sender": "helics-federate"}, "contents": {"measurements": [{"tag": "line-650632.kW", "value": 0.0, "ts": 0}, {"tag": "line-650632.kVAR", "value": 0.0, "ts": 0}, {"tag": "line-650632.closed", "value": 1.0, "ts": 0}, {"tag": "switch-671692.closed", "value": 1.0, "ts": 0}]}}
cpu    | 2023/09/01 10:23:12 [LOG] [modbus-outstation] setting tag line-650632.kW to value 0.000000
cpu    | 2023/09/01 10:23:12 [LOG] [modbus-outstation] setting tag line-650632.kVAR to value 0.000000
cpu    | 2023/09/01 10:23:12 [LOG] [modbus-outstation] setting tag line-650632.closed to value 1.000000
cpu    | 2023/09/01 10:23:12 [LOG] [modbus-outstation] setting tag switch-671692.closed to value 1.000000
cpu    | 2023/09/01 10:23:12 [LOG] [dnp3-outstation] status received for tag line-650632.kW
cpu    | 2023/09/01 10:23:12 [LOG] [dnp3-outstation] status received for tag line-650632.closed
cpu    | 2023/09/01 10:23:12 [LOG] [dnp3-outstation] updated binary input 0 to 1

```
From mbpoll:
```
Protocol configuration: Modbus TCP
Slave configuration...: address = [1]
                        start reference = 30000, count = 1
Communication.........: localhost, port 5502, t/o 1.00 s, poll rate 1000 ms
Data type.............: 16-bit register, input register table

-- Polling slave 1...
[30000]: 	0

```
I would greatly appreciate it if you could provide me with some pointers or hints to resolve this issue. Additionally, I plan to run the tests on a different machine, and I will keep you updated if I encounter the same output. Thank you for your assistance.

**Comment by activeshadow** [comment]
Hi @mzinfobeyond any luck with getting around this? I wish I could reproduce what you're seeing.

**Comment by mzinfobeyond** [comment]
Hello,

I'm still getting the same output, and I haven't had the opportunity to test it on a different machine yet. Do you believe that my issue might be related to Helics?

**Comment by activeshadow** [comment]
@mzinfobeyond okay so I was finally able to reproduce... it's likely because you're not using git LFS to pull down a few of the CSV files that make up the OpenDSS IEEE 13 bus test case.

Make sure you have the git-lfs package installed. Then, from the root of the repo, run `git lfs install && git lfs pull`. After that, things should work (you may have to rebuild the Docker image if you're using it).

Let me know...

**Comment by mzinfobeyond** [comment]
Hello @activeshadow ,

I appreciate your clarification. I've successfully installed `lfs` and can now observe the results. Thank you!
```
Protocol configuration: Modbus TCP
Slave configuration...: address = [1]
                        start reference = 30000, count = 1
Communication.........: localhost, port 5502, t/o 1.00 s, poll rate 1000 ms
Data type.............: 16-bit register, input register table

-- Polling slave 1...
[30000]: 	315
```
